### PR TITLE
Add new shorthands for some flags

### LINKED ISSUE #389: Workload create/apply supports additional shorthand flag values
### Description of problem

Flags likely to be used repeatedly are good candidates for single character shortcuts.
`tanzu apps workload create/apply` has several flags that would be valuable to shorthand.

#### Provide shorthand for each of the following flags:
* -a, --app  (prior art - `kctrl` and `kapp`)
* -e, --env (prior art - `docker`)
* -i, --image
* -l, --label (prior art - `kubectl`)
* -p, --param
* -t, --type

#### Help output
```
Flags:
      ...
  -a, --app name                       application name the workload is a part of
  -e, --env "key=value" pair           environment variables represented as a "key=value" pair ("key-" to remove, flag can be used multiple times)
  -i, --image image                    pre-built image, skips the source resolution and build phases of the supply chain
  -l, --label "key=value" pair         label is represented as a "key=value" pair ("key-" to remove, flag can be used multiple times)
  -p, --param "key=value" pair         additional parameters represented as a "key=value" pair ("key-" to remove, flag can be used multiple times)
  -t, --type type                      distinguish workload type
```

### PR DESCRIPTION
**Pull request by warango4**
Pull request

### What this PR does / why we need it
Add new shorthands for flags 

- -a, --app (prior art - kctrl and kapp)
- -e, --env (prior art - docker)
- -i, --image
- -l, --label (prior art - kubectl)
- -p, --param
- -t, --type

### Which issue(s) this PR fixes

Fixes #389 

### Additional information or special notes for your reviewer

Signed-off-by: Wendy Arango <warango@vmware.com>

### CODE REVIEW

**Comment by warango4** [comment]
image

**Comment by warango4** [comment]
image

**Review by odinnordico — APPROVED** [review]
LGTM

**Review by shaheerkootteeri — APPROVED** [review]
LGTM

**Review by anibmurthy — APPROVED** [review]

**Pull request merged**
